# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(max_length=100, verbose_name='姓名')),
                ('post_time', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('comment', models.TextField(max_length=2000, verbose_name='')),
                ('display', models.BooleanField(default=1)),
                ('uploads', models.FileField(blank=True, upload_to='note/%Y%m%d', verbose_name='附件')),
            ],
            options={
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(max_length=10000, verbose_name='内容')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('views', models.IntegerField(blank=True, default=1, verbose_name='浏览数')),
                ('poster_id', models.CharField(blank=True, default=1, max_length=100, verbose_name='作者')),
                ('original_url', models.URLField(blank=True)),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-update_time'],
                'verbose_name_plural': '学习笔记',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.ManyToManyField(blank=True, to='note.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Note'),
        ),
    ]
