# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签')),
            ],
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-update_time'], 'verbose_name_plural': '学习笔记'},
        ),
    ]
