# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20170115_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.ManyToManyField(blank=True, to='note.Tag'),
        ),
    ]
