# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_note_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_id', models.IntegerField(default=1)),
                ('post_time', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('comment', models.CharField(max_length=500, verbose_name='内容')),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.ManyToManyField(blank=True, to='note.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Note'),
        ),
    ]
