# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_auto_20170117_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='poster_id',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.ManyToManyField(blank=True, to='note.Tag'),
        ),
    ]
