# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_auto_20170117_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='poster_id',
            new_name='poster',
        ),
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.ManyToManyField(blank=True, to='note.Tag'),
        ),
    ]
