# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_auto_20170117_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uploads',
            field=models.FileField(blank=True, upload_to='note/%Y%M%D'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.ManyToManyField(blank=True, to='note.Tag'),
        ),
    ]
