# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_auto_20170118_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.ManyToManyField(blank=True, to='note.Tag'),
        ),
    ]
