# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_id', models.IntegerField(default=1)),
                ('post_time', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('comment', models.CharField(max_length=500, verbose_name='内容')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Note')),
            ],
        ),
    ]
